apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: partner-catalog-ec-pokh
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: partner-catalog-ec-pokh
    app.kubernetes.io/part-of: partner-catalog-ec
  name: partner-catalog-ec-pokh
spec:
  ports:
  - name: http-8081
    port: 8081
    protocol: TCP
    targetPort: 8081
  selector:
    app: java-springboot-app
    app.kubernetes.io/instance: partner-catalog-ec-pokh
status:
  loadBalancer: {}
